### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by duckworthd**
This PR adds module-, function-, and class-level docstrings and some in-code comments to summarize the magic that is Autograd.

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks, Daniel! These are great! I made a couple suggestions in chat; if you apply those, we should merge these docstrings and comments ASAP!

**Comment by puzzler10** [comment]
These docstrings are super useful. Any chance we can merge them in?

**Comment by EtoDemerzel0427** [comment]
Not sure why this pull request was not merged to the master branch, but it really helps a lot. Thanks Daniel!

**Comment by mattjj** [comment]
Thanks for the pings :) and thanks for this great PR!

**Pull request merged**
