### PR TITLE
Make some imports relative, fixing broken import in python3

### PR DESCRIPTION
**Pull request by csuter**
I was trying to play around with autodidact and found import broken in python3. This appears to fix it.

### CODE REVIEW

**Comment by csuter** [comment]
To be more precise, here are steps that reproduce the error I got (assumes virtualenv is around):

```
$ cd /tmp
$ virtualenv -p python3 autodidact
$ cd autodidact
$ source bin/activate
$ git clone https://github.com/mattjj/autodidact
$ cd autodidact
$ pip install numpy
$ python -c 'import autograd'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/autodidact/autodidact/autograd/__init__.py", line 1, in <module>
    from .differential_operators import make_vjp, grad
  File "/tmp/autodidact/autodidact/autograd/differential_operators.py", line 5, in <module>
    from .core import make_vjp
  File "/tmp/autodidact/autodidact/autograd/core.py", line 5, in <module>
    from tracer import trace, Node
ImportError: No module named 'tracer'
```

**Comment by quaffpotion** [comment]
I tried this and got: (With tanh.py in the autodidact folder instead of examples)

```
(autodidact) ➜  autodidact git:(master) ✗ python tanh.py
Traceback (most recent call last):
  File "tanh.py", line 10, in <module>
    print(grad(tanh)(1.0))
  File "/private/tmp/autodidact/autodidact/autograd/differential_operators.py", line 12, in gradfun
    return vjp(np.ones_like(ans))
  File "/private/tmp/autodidact/autodidact/autograd/core.py", line 14, in vjp
    def vjp(g): return backward_pass(g, end_node)
  File "/private/tmp/autodidact/autodidact/autograd/core.py", line 23, in backward_pass
    vjp = primitive_vjps[fun][argnum]
KeyError: 0
```

**Comment by tonyiota** [comment]
If I do this and run `tanh.py` in the autodidact directory (instead of from within examples) I get:

```
(autodidact) ➜  autodidact git:(master) ✗ python tanh.py
Traceback (most recent call last):
  File "tanh.py", line 10, in <module>
    print(grad(tanh)(1.0))
  File "/private/tmp/autodidact/autodidact/autograd/differential_operators.py", line 12, in gradfun
    return vjp(np.ones_like(ans))
  File "/private/tmp/autodidact/autodidact/autograd/core.py", line 14, in vjp
    def vjp(g): return backward_pass(g, end_node)
  File "/private/tmp/autodidact/autodidact/autograd/core.py", line 23, in backward_pass
    vjp = primitive_vjps[fun][argnum]
KeyError: 0
```

Seems you can fix this by using: get(....) : https://github.com/quaffpotion/autodidact/commit/82c808c5300674833f44d010959a96e930ec6ec3

**Comment by mattjj** [comment]
Sorry, somehow I missed this PR. I think the change is included in #6 (which I happened to merge first), so I'm going to close this one, but thanks for the fix!

**Pull request closed without merging**
